package rp3.cartera.model;

import android.database.Cursor;
import rp3.cartera.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;

public class ActividadCliente extends EntityBase<ActividadCliente> {

	private int idActividadCliente;
	private String nombre;
	private int activo;
	@Override
	public long getID() {
		// TODO Auto-generated method stub
		return getIdActividadCliente();
	}

	@Override
	public void setID(long id) {
		// TODO Auto-generated method stub
		setIdActividadCliente((int)id);
	}

	@Override
	public boolean isAutoGeneratedId() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return  Contract.ActividadCliente.TABLE_NAME;
	}

	@Override
	public void setValues() {
		// TODO Auto-generated method stub
		
	}
	public int getIdActividadCliente() {
		return idActividadCliente;
	}
	
	public void setIdActividadCliente(int idActividadCliente) {
		this.idActividadCliente= idActividadCliente;
	}
	
	public static Cursor getActividadClienteCursor(DataBase db){		
		return db.query(Contract.ActividadCliente.TABLE_NAME, new String[] { Contract.ActividadCliente._ID,  Contract.ActividadCliente.FIELD_NOMBRE } );
	}


}
