package rp3.cartera.model;
import android.database.Cursor;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.cartera.db.Contract;

public class CategoriaCliente  extends EntityBase<CategoriaCliente> {

	private int idCategoriaCliente;
	private String nombre;
	private int activo;
	
	
	@Override
	public long getID() {
		// TODO Auto-generated method stub
		return getIdCategoriaCliente();
	}

	@Override
	public void setID(long id) {
		// TODO Auto-generated method stub
		setIdCategoriaCliente((int)id);
	}

	@Override
	public boolean isAutoGeneratedId() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return Contract.CategoriaCliente.TABLE_NAME;
	}

	@Override
	public void setValues() {
		// TODO Auto-generated method stub
		
	}
	public int getIdCategoriaCliente() {
		return idCategoriaCliente;
	}
	
	public void setIdCategoriaCliente(int idCategoriaCliente) {
		this.idCategoriaCliente= idCategoriaCliente;
	}
	
	public static Cursor getCategoriaClienteCursor(DataBase db){		
		return db.query(Contract.CategoriaCliente.TABLE_NAME, new String[] { Contract.CategoriaCliente._ID,  Contract.CategoriaCliente.FIELD_NOMBRE } );
	}

}
