package rp3.cartera.model;

import android.database.Cursor;
import rp3.cartera.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;

public class EstructuraComercial extends EntityBase<EstructuraComercial>
{

	private int idEstructuraComercial;
	private String nombre;
	private int activo;
	private int nivel;
	private int idPadre;


	@Override
	public long getID() {
		// TODO Auto-generated method stub
		return getIdEstructuraComercial();
	}

	@Override
	public void setID(long id) {
		// TODO Auto-generated method stub
		setIdEstructuraComercial((int)id);
	}

	@Override
	public boolean isAutoGeneratedId() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setValues() {
		// TODO Auto-generated method stub
	}

	public int getIdEstructuraComercial() {
		return idEstructuraComercial;
	}
	
	public void setIdEstructuraComercial(int idEstructuraComercial) {
		this.idEstructuraComercial= idEstructuraComercial;
	}
	
	public static Cursor getEstructuraComercialCursor(DataBase db){		
		return db.query(Contract.EstructuraComercial.TABLE_NAME, new String[] { Contract.EstructuraComercial._ID,  Contract.EstructuraComercial.FIELD_NOMBRE } );
	}

}
