package rp3.cartera.model;

import android.database.Cursor;
import rp3.cartera.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;

public class Genero extends EntityBase<Genero> {


	private int idGenero;
	private String nombre;
	private int activo;
	@Override
	public long getID() {
		// TODO Auto-generated method stub
		return getIdGenero();
	}

	@Override
	public void setID(long id) {
		// TODO Auto-generated method stub
		setIdGenero((int)id);
	}

	@Override
	public boolean isAutoGeneratedId() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return Contract.Genero.TABLE_NAME;
	}

	@Override
	public void setValues() {
		// TODO Auto-generated method stub
		
	}
	public int getIdGenero() {
		return idGenero;
	}
	
	public void setIdGenero(int idGenero) {
		this.idGenero= idGenero;
	}
	
	public static Cursor getGeneroCursor(DataBase db){		
		return db.query(Contract.Genero.TABLE_NAME, new String[] { Contract.Genero._ID,  Contract.Genero.FIELD_NOMBRE } );
	}

}
