package rp3.cartera.model;

import android.database.Cursor;
import rp3.cartera.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;

public class MovimientoCliente extends EntityBase<MovimientoCliente> {

	private int idMovimientoCliente;

	@Override
	public long getID() {
		// TODO Auto-generated method stub
		return getIdMovimientoCliente();
	}

	@Override
	public void setID(long id) {
		// TODO Auto-generated method stub
		setIdMovimientoCliente((int) id);
	}

	@Override
	public boolean isAutoGeneratedId() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return Contract.MovimientoCliente.TABLE_NAME;
	}

	@Override
	public void setValues() {
		// TODO Auto-generated method stub

	}

	public int getIdMovimientoCliente() {
		return idMovimientoCliente;
	}

	public void setIdMovimientoCliente(int idMovimientoCliente) {
		this.idMovimientoCliente = idMovimientoCliente;
	}

	public static Cursor getMovimientoClienteCursor(DataBase db, int idCliente) {

		return db.query(Contract.MovimientoCliente.TABLE_NAME, new String[] {
				Contract.MovimientoCliente._ID,
				Contract.MovimientoCliente.FIELD_TIPODOCUMENTO,
				Contract.MovimientoCliente.FIELD_DOCUMENTO,
				Contract.MovimientoCliente.COLUMN_FECHAMOVIMIENTO,
				Contract.MovimientoCliente.COLUMN_TOTAL,
				Contract.MovimientoCliente.FIELD_DEBITO,
				Contract.MovimientoCliente.FIELD_CREDITO,
				Contract.MovimientoCliente.FIELD_SALDO });
	}

}
