package rp3.cartera.model;

import android.database.Cursor;
import rp3.cartera.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;

public class TipoCliente extends EntityBase<TipoCliente> {

	
	private int idTipoCliente;
	private String nombre;
	private int activo;
	
	@Override
	public long getID() {
		// TODO Auto-generated method stub
		return getIdTipoCliente();
	}

	@Override
	public void setID(long id) {
		// TODO Auto-generated method stub
		setIdTipoCliente((int)id);
	}

	@Override
	public boolean isAutoGeneratedId() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return Contract.TipoCliente.TABLE_NAME;
	}

	@Override
	public void setValues() {
		// TODO Auto-generated method stub
		
	}
	
	public int getIdTipoCliente() {
		return idTipoCliente;
	}
	
	public void setIdTipoCliente(int idTipoCliente) {
		this.idTipoCliente= idTipoCliente;
	}
	
	public static Cursor getTipoClienteCursor(DataBase db){		
		return db.query(Contract.TipoCliente.TABLE_NAME, new String[] { Contract.TipoCliente._ID,  Contract.TipoCliente.FIELD_NOMBRE } );
	}


}
