package rp3.cartera.model;

import android.database.Cursor;
import rp3.cartera.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;

public class Zona extends EntityBase<Zona> {

	private int idZona;
	private String nombre;
	private int activo;
	
	@Override
	public long getID() {
		// TODO Auto-generated method stub
		return getIdZona();
	}

	@Override
	public void setID(long id) {
		// TODO Auto-generated method stub
		setIdZona((int)id);
	}

	@Override
	public boolean isAutoGeneratedId() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return Contract.Zona.TABLE_NAME;
	}

	@Override
	public void setValues() {
		// TODO Auto-generated method stub
		
	}

	public int getIdZona() {
		return idZona;
	}
	
	public void setIdZona(int idZona) {
		this.idZona= idZona;
	}
	
	public static Cursor getZonaCursor(DataBase db){		
		return db.query(Contract.Zona.TABLE_NAME, new String[] { Contract.Zona._ID,  Contract.Zona.FIELD_NOMBRE } );
	}

}
